# Generated by Django 4.2.7 on 2024-04-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishs',
            name='discount',
            field=models.IntegerField(default=0, max_length=2, verbose_name='Знижка у %'),
        ),
    ]
