# Generated by Django 4.2.7 on 2024-04-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_dishs_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishs',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='Знижка у %'),
        ),
    ]
