# Generated by Django 4.2.7 on 2024-04-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_dishs_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dishs',
            options={'ordering': ('id',), 'verbose_name': 'Страву', 'verbose_name_plural': 'Страви'},
        ),
        migrations.AddField(
            model_name='categories',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories_icons', verbose_name='Іконка категорії'),
        ),
    ]
